[package]
name = "todo_list_shared"
version = "0.1.0"
edition = "2021"
author = "Daohan Chong <wildcat.name@gmail.com>"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
