name: Swift

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build
      run: |
          make prepare-apple
          cd hello
          make all

    - name: 'Upload xcframework'
      uses: actions/upload-artifact@v2
      with:
        name: HelloFFI.xcframework
        path: hello/target/HelloFFI.xcframework
        retention-days: 7